/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.izhengyin.test.hadoop.avro;

import org.apache.avro.Schema;

import java.io.IOException;
import java.io.ObjectInput;
import java.io.ObjectOutput;

@SuppressWarnings("all")
@org.apache.avro.specific.FixedSize(16)
@org.apache.avro.specific.AvroGenerated
public class md5 extends org.apache.avro.specific.SpecificFixed {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"fixed\",\"name\":\"md5\",\"namespace\":\"com.izhengyin.test.hadoop.avro\",\"size\":16}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  /** Creates a new md5 */
  public md5() {
    super();
  }

  /** Creates a new md5 with the given bytes */
  public md5(byte[] bytes) {
    super(bytes);
  }

  @Override
  public Schema getSchema() {
    return SCHEMA$;
  }

  @Override
  public void writeExternal(ObjectOutput objectOutput) throws IOException {

  }

  @Override
  public void readExternal(ObjectInput objectInput) throws IOException {

  }
}
