/**
 * Autogenerated by Avro
 * DO NOT EDIT DIRECTLY
 */
package com.izhengyin.test.other.serial;

import java.util.HashMap;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class Events extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Events\",\"namespace\":\"com.izhengyin.test.other.serial\",\"fields\":[{\"name\":\"id\",\"type\":\"long\"},{\"name\":\"event\",\"type\":\"string\"},{\"name\":\"platform\",\"type\":\"string\"},{\"name\":\"client\",\"type\":\"string\"},{\"name\":\"shop_id\",\"type\":\"int\"},{\"name\":\"user_id\",\"type\":\"int\"},{\"name\":\"seller_id\",\"type\":\"int\"},{\"name\":\"type\",\"type\":\"string\"},{\"name\":\"uuid\",\"type\":\"string\"},{\"name\":\"utm_source\",\"type\":\"string\"},{\"name\":\"resolution\",\"type\":\"string\"},{\"name\":\"client_ip\",\"type\":\"string\"},{\"name\":\"user_agent\",\"type\":\"string\"},{\"name\":\"country\",\"type\":\"string\"},{\"name\":\"province\",\"type\":\"string\"},{\"name\":\"city\",\"type\":\"string\"},{\"name\":\"self_page\",\"type\":\"string\"},{\"name\":\"ref_page\",\"type\":\"string\"},{\"name\":\"session_id\",\"type\":\"string\"},{\"name\":\"session_duration\",\"type\":\"string\"},{\"name\":\"app_name\",\"type\":\"string\"},{\"name\":\"app_version\",\"type\":\"string\"},{\"name\":\"event_date\",\"type\":\"string\"},{\"name\":\"event_time\",\"type\":\"long\"},{\"name\":\"event_time_ms\",\"type\":\"long\"},{\"name\":\"platform_attr\",\"type\":{\"type\":\"map\",\"values\":\"string\"}},{\"name\":\"count_attr\",\"type\":{\"type\":\"map\",\"values\":\"int\"}},{\"name\":\"event_attr\",\"type\":{\"type\":\"map\",\"values\":\"string\"}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public long id = 0;
  @Deprecated public CharSequence event = "";
  @Deprecated public CharSequence platform = "";;
  @Deprecated public CharSequence client = "";;
  @Deprecated public int shop_id = 0;
  @Deprecated public int user_id = 0;
  @Deprecated public int seller_id = 0;
  @Deprecated public CharSequence type = "";
  @Deprecated public CharSequence uuid= "";
  @Deprecated public CharSequence utm_source= "";
  @Deprecated public CharSequence resolution= "";
  @Deprecated public CharSequence client_ip= "";
  @Deprecated public CharSequence user_agent= "";
  @Deprecated public CharSequence country= "";
  @Deprecated public CharSequence province= "";
  @Deprecated public CharSequence city= "";
  @Deprecated public CharSequence self_page= "";
  @Deprecated public CharSequence ref_page= "";
  @Deprecated public CharSequence session_id= "";
  @Deprecated public CharSequence session_duration= "";
  @Deprecated public CharSequence app_name= "";
  @Deprecated public CharSequence app_version= "";
  @Deprecated public CharSequence event_date= "";
  @Deprecated public long event_time = 0;
  @Deprecated public long event_time_ms = 0;
  @Deprecated public java.util.Map<CharSequence,CharSequence> platform_attr = new HashMap<CharSequence,CharSequence>();
  @Deprecated public java.util.Map<CharSequence,Integer> count_attr = new HashMap<CharSequence,Integer>();
  @Deprecated public java.util.Map<CharSequence,CharSequence> event_attr = new HashMap<CharSequence,CharSequence>();

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Events() {}

  /**
   * All-args constructor.
   */
  public Events(Long id, CharSequence event, CharSequence platform, CharSequence client, Integer shop_id, Integer user_id, Integer seller_id, CharSequence type, CharSequence uuid, CharSequence utm_source, CharSequence resolution, CharSequence client_ip, CharSequence user_agent, CharSequence country, CharSequence province, CharSequence city, CharSequence self_page, CharSequence ref_page, CharSequence session_id, CharSequence session_duration, CharSequence app_name, CharSequence app_version, CharSequence event_date, Long event_time, Long event_time_ms, java.util.Map<CharSequence,CharSequence> platform_attr, java.util.Map<CharSequence,Integer> count_attr, java.util.Map<CharSequence,CharSequence> event_attr) {
    this.id = id;
    this.event = event;
    this.platform = platform;
    this.client = client;
    this.shop_id = shop_id;
    this.user_id = user_id;
    this.seller_id = seller_id;
    this.type = type;
    this.uuid = uuid;
    this.utm_source = utm_source;
    this.resolution = resolution;
    this.client_ip = client_ip;
    this.user_agent = user_agent;
    this.country = country;
    this.province = province;
    this.city = city;
    this.self_page = self_page;
    this.ref_page = ref_page;
    this.session_id = session_id;
    this.session_duration = session_duration;
    this.app_name = app_name;
    this.app_version = app_version;
    this.event_date = event_date;
    this.event_time = event_time;
    this.event_time_ms = event_time_ms;
    this.platform_attr = platform_attr;
    this.count_attr = count_attr;
    this.event_attr = event_attr;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public Object get(int field$) {
    switch (field$) {
    case 0: return id;
    case 1: return event;
    case 2: return platform;
    case 3: return client;
    case 4: return shop_id;
    case 5: return user_id;
    case 6: return seller_id;
    case 7: return type;
    case 8: return uuid;
    case 9: return utm_source;
    case 10: return resolution;
    case 11: return client_ip;
    case 12: return user_agent;
    case 13: return country;
    case 14: return province;
    case 15: return city;
    case 16: return self_page;
    case 17: return ref_page;
    case 18: return session_id;
    case 19: return session_duration;
    case 20: return app_name;
    case 21: return app_version;
    case 22: return event_date;
    case 23: return event_time;
    case 24: return event_time_ms;
    case 25: return platform_attr;
    case 26: return count_attr;
    case 27: return event_attr;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, Object value$) {
    switch (field$) {
    case 0: id = (Long)value$; break;
    case 1: event = (CharSequence)value$; break;
    case 2: platform = (CharSequence)value$; break;
    case 3: client = (CharSequence)value$; break;
    case 4: shop_id = (Integer)value$; break;
    case 5: user_id = (Integer)value$; break;
    case 6: seller_id = (Integer)value$; break;
    case 7: type = (CharSequence)value$; break;
    case 8: uuid = (CharSequence)value$; break;
    case 9: utm_source = (CharSequence)value$; break;
    case 10: resolution = (CharSequence)value$; break;
    case 11: client_ip = (CharSequence)value$; break;
    case 12: user_agent = (CharSequence)value$; break;
    case 13: country = (CharSequence)value$; break;
    case 14: province = (CharSequence)value$; break;
    case 15: city = (CharSequence)value$; break;
    case 16: self_page = (CharSequence)value$; break;
    case 17: ref_page = (CharSequence)value$; break;
    case 18: session_id = (CharSequence)value$; break;
    case 19: session_duration = (CharSequence)value$; break;
    case 20: app_name = (CharSequence)value$; break;
    case 21: app_version = (CharSequence)value$; break;
    case 22: event_date = (CharSequence)value$; break;
    case 23: event_time = (Long)value$; break;
    case 24: event_time_ms = (Long)value$; break;
    case 25: platform_attr = (java.util.Map<CharSequence,CharSequence>)value$; break;
    case 26: count_attr = (java.util.Map<CharSequence,Integer>)value$; break;
    case 27: event_attr = (java.util.Map<CharSequence,CharSequence>)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'id' field.
   */
  public Long getId() {
    return id;
  }

  /**
   * Sets the value of the 'id' field.
   * @param value the value to set.
   */
  public void setId(Long value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'event' field.
   */
  public CharSequence getEvent() {
    return event;
  }

  /**
   * Sets the value of the 'event' field.
   * @param value the value to set.
   */
  public void setEvent(CharSequence value) {
    this.event = value;
  }

  /**
   * Gets the value of the 'platform' field.
   */
  public CharSequence getPlatform() {
    return platform;
  }

  /**
   * Sets the value of the 'platform' field.
   * @param value the value to set.
   */
  public void setPlatform(CharSequence value) {
    this.platform = value;
  }

  /**
   * Gets the value of the 'client' field.
   */
  public CharSequence getClient() {
    return client;
  }

  /**
   * Sets the value of the 'client' field.
   * @param value the value to set.
   */
  public void setClient(CharSequence value) {
    this.client = value;
  }

  /**
   * Gets the value of the 'shop_id' field.
   */
  public Integer getShopId() {
    return shop_id;
  }

  /**
   * Sets the value of the 'shop_id' field.
   * @param value the value to set.
   */
  public void setShopId(Integer value) {
    this.shop_id = value;
  }

  /**
   * Gets the value of the 'user_id' field.
   */
  public Integer getUserId() {
    return user_id;
  }

  /**
   * Sets the value of the 'user_id' field.
   * @param value the value to set.
   */
  public void setUserId(Integer value) {
    this.user_id = value;
  }

  /**
   * Gets the value of the 'seller_id' field.
   */
  public Integer getSellerId() {
    return seller_id;
  }

  /**
   * Sets the value of the 'seller_id' field.
   * @param value the value to set.
   */
  public void setSellerId(Integer value) {
    this.seller_id = value;
  }

  /**
   * Gets the value of the 'type' field.
   */
  public CharSequence getType() {
    return type;
  }

  /**
   * Sets the value of the 'type' field.
   * @param value the value to set.
   */
  public void setType(CharSequence value) {
    this.type = value;
  }

  /**
   * Gets the value of the 'uuid' field.
   */
  public CharSequence getUuid() {
    return uuid;
  }

  /**
   * Sets the value of the 'uuid' field.
   * @param value the value to set.
   */
  public void setUuid(CharSequence value) {
    this.uuid = value;
  }

  /**
   * Gets the value of the 'utm_source' field.
   */
  public CharSequence getUtmSource() {
    return utm_source;
  }

  /**
   * Sets the value of the 'utm_source' field.
   * @param value the value to set.
   */
  public void setUtmSource(CharSequence value) {
    this.utm_source = value;
  }

  /**
   * Gets the value of the 'resolution' field.
   */
  public CharSequence getResolution() {
    return resolution;
  }

  /**
   * Sets the value of the 'resolution' field.
   * @param value the value to set.
   */
  public void setResolution(CharSequence value) {
    this.resolution = value;
  }

  /**
   * Gets the value of the 'client_ip' field.
   */
  public CharSequence getClientIp() {
    return client_ip;
  }

  /**
   * Sets the value of the 'client_ip' field.
   * @param value the value to set.
   */
  public void setClientIp(CharSequence value) {
    this.client_ip = value;
  }

  /**
   * Gets the value of the 'user_agent' field.
   */
  public CharSequence getUserAgent() {
    return user_agent;
  }

  /**
   * Sets the value of the 'user_agent' field.
   * @param value the value to set.
   */
  public void setUserAgent(CharSequence value) {
    this.user_agent = value;
  }

  /**
   * Gets the value of the 'country' field.
   */
  public CharSequence getCountry() {
    return country;
  }

  /**
   * Sets the value of the 'country' field.
   * @param value the value to set.
   */
  public void setCountry(CharSequence value) {
    this.country = value;
  }

  /**
   * Gets the value of the 'province' field.
   */
  public CharSequence getProvince() {
    return province;
  }

  /**
   * Sets the value of the 'province' field.
   * @param value the value to set.
   */
  public void setProvince(CharSequence value) {
    this.province = value;
  }

  /**
   * Gets the value of the 'city' field.
   */
  public CharSequence getCity() {
    return city;
  }

  /**
   * Sets the value of the 'city' field.
   * @param value the value to set.
   */
  public void setCity(CharSequence value) {
    this.city = value;
  }

  /**
   * Gets the value of the 'self_page' field.
   */
  public CharSequence getSelfPage() {
    return self_page;
  }

  /**
   * Sets the value of the 'self_page' field.
   * @param value the value to set.
   */
  public void setSelfPage(CharSequence value) {
    this.self_page = value;
  }

  /**
   * Gets the value of the 'ref_page' field.
   */
  public CharSequence getRefPage() {
    return ref_page;
  }

  /**
   * Sets the value of the 'ref_page' field.
   * @param value the value to set.
   */
  public void setRefPage(CharSequence value) {
    this.ref_page = value;
  }

  /**
   * Gets the value of the 'session_id' field.
   */
  public CharSequence getSessionId() {
    return session_id;
  }

  /**
   * Sets the value of the 'session_id' field.
   * @param value the value to set.
   */
  public void setSessionId(CharSequence value) {
    this.session_id = value;
  }

  /**
   * Gets the value of the 'session_duration' field.
   */
  public CharSequence getSessionDuration() {
    return session_duration;
  }

  /**
   * Sets the value of the 'session_duration' field.
   * @param value the value to set.
   */
  public void setSessionDuration(CharSequence value) {
    this.session_duration = value;
  }

  /**
   * Gets the value of the 'app_name' field.
   */
  public CharSequence getAppName() {
    return app_name;
  }

  /**
   * Sets the value of the 'app_name' field.
   * @param value the value to set.
   */
  public void setAppName(CharSequence value) {
    this.app_name = value;
  }

  /**
   * Gets the value of the 'app_version' field.
   */
  public CharSequence getAppVersion() {
    return app_version;
  }

  /**
   * Sets the value of the 'app_version' field.
   * @param value the value to set.
   */
  public void setAppVersion(CharSequence value) {
    this.app_version = value;
  }

  /**
   * Gets the value of the 'event_date' field.
   */
  public CharSequence getEventDate() {
    return event_date;
  }

  /**
   * Sets the value of the 'event_date' field.
   * @param value the value to set.
   */
  public void setEventDate(CharSequence value) {
    this.event_date = value;
  }

  /**
   * Gets the value of the 'event_time' field.
   */
  public Long getEventTime() {
    return event_time;
  }

  /**
   * Sets the value of the 'event_time' field.
   * @param value the value to set.
   */
  public void setEventTime(Long value) {
    this.event_time = value;
  }

  /**
   * Gets the value of the 'event_time_ms' field.
   */
  public Long getEventTimeMs() {
    return event_time_ms;
  }

  /**
   * Sets the value of the 'event_time_ms' field.
   * @param value the value to set.
   */
  public void setEventTimeMs(Long value) {
    this.event_time_ms = value;
  }

  /**
   * Gets the value of the 'platform_attr' field.
   */
  public java.util.Map<CharSequence,CharSequence> getPlatformAttr() {
    return platform_attr;
  }

  /**
   * Sets the value of the 'platform_attr' field.
   * @param value the value to set.
   */
  public void setPlatformAttr(java.util.Map<CharSequence,CharSequence> value) {
    this.platform_attr = value;
  }

  /**
   * Gets the value of the 'count_attr' field.
   */
  public java.util.Map<CharSequence,Integer> getCountAttr() {
    return count_attr;
  }

  /**
   * Sets the value of the 'count_attr' field.
   * @param value the value to set.
   */
  public void setCountAttr(java.util.Map<CharSequence,Integer> value) {
    this.count_attr = value;
  }

  /**
   * Gets the value of the 'event_attr' field.
   */
  public java.util.Map<CharSequence,CharSequence> getEventAttr() {
    return event_attr;
  }

  /**
   * Sets the value of the 'event_attr' field.
   * @param value the value to set.
   */
  public void setEventAttr(java.util.Map<CharSequence,CharSequence> value) {
    this.event_attr = value;
  }

  /** Creates a new Events RecordBuilder */
  public static com.izhengyin.test.other.serial.Events.Builder newBuilder() {
    return new com.izhengyin.test.other.serial.Events.Builder();
  }

  /** Creates a new Events RecordBuilder by copying an existing Builder */
  public static com.izhengyin.test.other.serial.Events.Builder newBuilder(com.izhengyin.test.other.serial.Events.Builder other) {
    return new com.izhengyin.test.other.serial.Events.Builder(other);
  }

  /** Creates a new Events RecordBuilder by copying an existing Events instance */
  public static com.izhengyin.test.other.serial.Events.Builder newBuilder(com.izhengyin.test.other.serial.Events other) {
    return new com.izhengyin.test.other.serial.Events.Builder(other);
  }

  /**
   * RecordBuilder for Events instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Events>
    implements org.apache.avro.data.RecordBuilder<Events> {

    private long id;
    private CharSequence event;
    private CharSequence platform;
    private CharSequence client;
    private int shop_id;
    private int user_id;
    private int seller_id;
    private CharSequence type;
    private CharSequence uuid;
    private CharSequence utm_source;
    private CharSequence resolution;
    private CharSequence client_ip;
    private CharSequence user_agent;
    private CharSequence country;
    private CharSequence province;
    private CharSequence city;
    private CharSequence self_page;
    private CharSequence ref_page;
    private CharSequence session_id;
    private CharSequence session_duration;
    private CharSequence app_name;
    private CharSequence app_version;
    private CharSequence event_date;
    private long event_time;
    private long event_time_ms;
    private java.util.Map<CharSequence,CharSequence> platform_attr;
    private java.util.Map<CharSequence,Integer> count_attr;
    private java.util.Map<CharSequence,CharSequence> event_attr;

    /** Creates a new Builder */
    private Builder() {
      super(com.izhengyin.test.other.serial.Events.SCHEMA$);
    }

    /** Creates a Builder by copying an existing Builder */
    private Builder(com.izhengyin.test.other.serial.Events.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.event)) {
        this.event = data().deepCopy(fields()[1].schema(), other.event);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.platform)) {
        this.platform = data().deepCopy(fields()[2].schema(), other.platform);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.client)) {
        this.client = data().deepCopy(fields()[3].schema(), other.client);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.shop_id)) {
        this.shop_id = data().deepCopy(fields()[4].schema(), other.shop_id);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.user_id)) {
        this.user_id = data().deepCopy(fields()[5].schema(), other.user_id);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.seller_id)) {
        this.seller_id = data().deepCopy(fields()[6].schema(), other.seller_id);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.type)) {
        this.type = data().deepCopy(fields()[7].schema(), other.type);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.uuid)) {
        this.uuid = data().deepCopy(fields()[8].schema(), other.uuid);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.utm_source)) {
        this.utm_source = data().deepCopy(fields()[9].schema(), other.utm_source);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.resolution)) {
        this.resolution = data().deepCopy(fields()[10].schema(), other.resolution);
        fieldSetFlags()[10] = true;
      }
      if (isValidValue(fields()[11], other.client_ip)) {
        this.client_ip = data().deepCopy(fields()[11].schema(), other.client_ip);
        fieldSetFlags()[11] = true;
      }
      if (isValidValue(fields()[12], other.user_agent)) {
        this.user_agent = data().deepCopy(fields()[12].schema(), other.user_agent);
        fieldSetFlags()[12] = true;
      }
      if (isValidValue(fields()[13], other.country)) {
        this.country = data().deepCopy(fields()[13].schema(), other.country);
        fieldSetFlags()[13] = true;
      }
      if (isValidValue(fields()[14], other.province)) {
        this.province = data().deepCopy(fields()[14].schema(), other.province);
        fieldSetFlags()[14] = true;
      }
      if (isValidValue(fields()[15], other.city)) {
        this.city = data().deepCopy(fields()[15].schema(), other.city);
        fieldSetFlags()[15] = true;
      }
      if (isValidValue(fields()[16], other.self_page)) {
        this.self_page = data().deepCopy(fields()[16].schema(), other.self_page);
        fieldSetFlags()[16] = true;
      }
      if (isValidValue(fields()[17], other.ref_page)) {
        this.ref_page = data().deepCopy(fields()[17].schema(), other.ref_page);
        fieldSetFlags()[17] = true;
      }
      if (isValidValue(fields()[18], other.session_id)) {
        this.session_id = data().deepCopy(fields()[18].schema(), other.session_id);
        fieldSetFlags()[18] = true;
      }
      if (isValidValue(fields()[19], other.session_duration)) {
        this.session_duration = data().deepCopy(fields()[19].schema(), other.session_duration);
        fieldSetFlags()[19] = true;
      }
      if (isValidValue(fields()[20], other.app_name)) {
        this.app_name = data().deepCopy(fields()[20].schema(), other.app_name);
        fieldSetFlags()[20] = true;
      }
      if (isValidValue(fields()[21], other.app_version)) {
        this.app_version = data().deepCopy(fields()[21].schema(), other.app_version);
        fieldSetFlags()[21] = true;
      }
      if (isValidValue(fields()[22], other.event_date)) {
        this.event_date = data().deepCopy(fields()[22].schema(), other.event_date);
        fieldSetFlags()[22] = true;
      }
      if (isValidValue(fields()[23], other.event_time)) {
        this.event_time = data().deepCopy(fields()[23].schema(), other.event_time);
        fieldSetFlags()[23] = true;
      }
      if (isValidValue(fields()[24], other.event_time_ms)) {
        this.event_time_ms = data().deepCopy(fields()[24].schema(), other.event_time_ms);
        fieldSetFlags()[24] = true;
      }
      if (isValidValue(fields()[25], other.platform_attr)) {
        this.platform_attr = data().deepCopy(fields()[25].schema(), other.platform_attr);
        fieldSetFlags()[25] = true;
      }
      if (isValidValue(fields()[26], other.count_attr)) {
        this.count_attr = data().deepCopy(fields()[26].schema(), other.count_attr);
        fieldSetFlags()[26] = true;
      }
      if (isValidValue(fields()[27], other.event_attr)) {
        this.event_attr = data().deepCopy(fields()[27].schema(), other.event_attr);
        fieldSetFlags()[27] = true;
      }
    }

    /** Creates a Builder by copying an existing Events instance */
    private Builder(com.izhengyin.test.other.serial.Events other) {
            super(com.izhengyin.test.other.serial.Events.SCHEMA$);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.event)) {
        this.event = data().deepCopy(fields()[1].schema(), other.event);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.platform)) {
        this.platform = data().deepCopy(fields()[2].schema(), other.platform);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.client)) {
        this.client = data().deepCopy(fields()[3].schema(), other.client);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.shop_id)) {
        this.shop_id = data().deepCopy(fields()[4].schema(), other.shop_id);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.user_id)) {
        this.user_id = data().deepCopy(fields()[5].schema(), other.user_id);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.seller_id)) {
        this.seller_id = data().deepCopy(fields()[6].schema(), other.seller_id);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.type)) {
        this.type = data().deepCopy(fields()[7].schema(), other.type);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.uuid)) {
        this.uuid = data().deepCopy(fields()[8].schema(), other.uuid);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.utm_source)) {
        this.utm_source = data().deepCopy(fields()[9].schema(), other.utm_source);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.resolution)) {
        this.resolution = data().deepCopy(fields()[10].schema(), other.resolution);
        fieldSetFlags()[10] = true;
      }
      if (isValidValue(fields()[11], other.client_ip)) {
        this.client_ip = data().deepCopy(fields()[11].schema(), other.client_ip);
        fieldSetFlags()[11] = true;
      }
      if (isValidValue(fields()[12], other.user_agent)) {
        this.user_agent = data().deepCopy(fields()[12].schema(), other.user_agent);
        fieldSetFlags()[12] = true;
      }
      if (isValidValue(fields()[13], other.country)) {
        this.country = data().deepCopy(fields()[13].schema(), other.country);
        fieldSetFlags()[13] = true;
      }
      if (isValidValue(fields()[14], other.province)) {
        this.province = data().deepCopy(fields()[14].schema(), other.province);
        fieldSetFlags()[14] = true;
      }
      if (isValidValue(fields()[15], other.city)) {
        this.city = data().deepCopy(fields()[15].schema(), other.city);
        fieldSetFlags()[15] = true;
      }
      if (isValidValue(fields()[16], other.self_page)) {
        this.self_page = data().deepCopy(fields()[16].schema(), other.self_page);
        fieldSetFlags()[16] = true;
      }
      if (isValidValue(fields()[17], other.ref_page)) {
        this.ref_page = data().deepCopy(fields()[17].schema(), other.ref_page);
        fieldSetFlags()[17] = true;
      }
      if (isValidValue(fields()[18], other.session_id)) {
        this.session_id = data().deepCopy(fields()[18].schema(), other.session_id);
        fieldSetFlags()[18] = true;
      }
      if (isValidValue(fields()[19], other.session_duration)) {
        this.session_duration = data().deepCopy(fields()[19].schema(), other.session_duration);
        fieldSetFlags()[19] = true;
      }
      if (isValidValue(fields()[20], other.app_name)) {
        this.app_name = data().deepCopy(fields()[20].schema(), other.app_name);
        fieldSetFlags()[20] = true;
      }
      if (isValidValue(fields()[21], other.app_version)) {
        this.app_version = data().deepCopy(fields()[21].schema(), other.app_version);
        fieldSetFlags()[21] = true;
      }
      if (isValidValue(fields()[22], other.event_date)) {
        this.event_date = data().deepCopy(fields()[22].schema(), other.event_date);
        fieldSetFlags()[22] = true;
      }
      if (isValidValue(fields()[23], other.event_time)) {
        this.event_time = data().deepCopy(fields()[23].schema(), other.event_time);
        fieldSetFlags()[23] = true;
      }
      if (isValidValue(fields()[24], other.event_time_ms)) {
        this.event_time_ms = data().deepCopy(fields()[24].schema(), other.event_time_ms);
        fieldSetFlags()[24] = true;
      }
      if (isValidValue(fields()[25], other.platform_attr)) {
        this.platform_attr = data().deepCopy(fields()[25].schema(), other.platform_attr);
        fieldSetFlags()[25] = true;
      }
      if (isValidValue(fields()[26], other.count_attr)) {
        this.count_attr = data().deepCopy(fields()[26].schema(), other.count_attr);
        fieldSetFlags()[26] = true;
      }
      if (isValidValue(fields()[27], other.event_attr)) {
        this.event_attr = data().deepCopy(fields()[27].schema(), other.event_attr);
        fieldSetFlags()[27] = true;
      }
    }

    /** Gets the value of the 'id' field */
    public Long getId() {
      return id;
    }

    /** Sets the value of the 'id' field */
    public com.izhengyin.test.other.serial.Events.Builder setId(long value) {
      validate(fields()[0], value);
      this.id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /** Checks whether the 'id' field has been set */
    public boolean hasId() {
      return fieldSetFlags()[0];
    }

    /** Clears the value of the 'id' field */
    public com.izhengyin.test.other.serial.Events.Builder clearId() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'event' field */
    public CharSequence getEvent() {
      return event;
    }

    /** Sets the value of the 'event' field */
    public com.izhengyin.test.other.serial.Events.Builder setEvent(CharSequence value) {
      validate(fields()[1], value);
      this.event = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /** Checks whether the 'event' field has been set */
    public boolean hasEvent() {
      return fieldSetFlags()[1];
    }

    /** Clears the value of the 'event' field */
    public com.izhengyin.test.other.serial.Events.Builder clearEvent() {
      event = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /** Gets the value of the 'platform' field */
    public CharSequence getPlatform() {
      return platform;
    }

    /** Sets the value of the 'platform' field */
    public com.izhengyin.test.other.serial.Events.Builder setPlatform(CharSequence value) {
      validate(fields()[2], value);
      this.platform = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /** Checks whether the 'platform' field has been set */
    public boolean hasPlatform() {
      return fieldSetFlags()[2];
    }

    /** Clears the value of the 'platform' field */
    public com.izhengyin.test.other.serial.Events.Builder clearPlatform() {
      platform = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /** Gets the value of the 'client' field */
    public CharSequence getClient() {
      return client;
    }

    /** Sets the value of the 'client' field */
    public com.izhengyin.test.other.serial.Events.Builder setClient(CharSequence value) {
      validate(fields()[3], value);
      this.client = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /** Checks whether the 'client' field has been set */
    public boolean hasClient() {
      return fieldSetFlags()[3];
    }

    /** Clears the value of the 'client' field */
    public com.izhengyin.test.other.serial.Events.Builder clearClient() {
      client = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /** Gets the value of the 'shop_id' field */
    public Integer getShopId() {
      return shop_id;
    }

    /** Sets the value of the 'shop_id' field */
    public com.izhengyin.test.other.serial.Events.Builder setShopId(int value) {
      validate(fields()[4], value);
      this.shop_id = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /** Checks whether the 'shop_id' field has been set */
    public boolean hasShopId() {
      return fieldSetFlags()[4];
    }

    /** Clears the value of the 'shop_id' field */
    public com.izhengyin.test.other.serial.Events.Builder clearShopId() {
      fieldSetFlags()[4] = false;
      return this;
    }

    /** Gets the value of the 'user_id' field */
    public Integer getUserId() {
      return user_id;
    }

    /** Sets the value of the 'user_id' field */
    public com.izhengyin.test.other.serial.Events.Builder setUserId(int value) {
      validate(fields()[5], value);
      this.user_id = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /** Checks whether the 'user_id' field has been set */
    public boolean hasUserId() {
      return fieldSetFlags()[5];
    }

    /** Clears the value of the 'user_id' field */
    public com.izhengyin.test.other.serial.Events.Builder clearUserId() {
      fieldSetFlags()[5] = false;
      return this;
    }

    /** Gets the value of the 'seller_id' field */
    public Integer getSellerId() {
      return seller_id;
    }

    /** Sets the value of the 'seller_id' field */
    public com.izhengyin.test.other.serial.Events.Builder setSellerId(int value) {
      validate(fields()[6], value);
      this.seller_id = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /** Checks whether the 'seller_id' field has been set */
    public boolean hasSellerId() {
      return fieldSetFlags()[6];
    }

    /** Clears the value of the 'seller_id' field */
    public com.izhengyin.test.other.serial.Events.Builder clearSellerId() {
      fieldSetFlags()[6] = false;
      return this;
    }

    /** Gets the value of the 'type' field */
    public CharSequence getType() {
      return type;
    }

    /** Sets the value of the 'type' field */
    public com.izhengyin.test.other.serial.Events.Builder setType(CharSequence value) {
      validate(fields()[7], value);
      this.type = value;
      fieldSetFlags()[7] = true;
      return this;
    }

    /** Checks whether the 'type' field has been set */
    public boolean hasType() {
      return fieldSetFlags()[7];
    }

    /** Clears the value of the 'type' field */
    public com.izhengyin.test.other.serial.Events.Builder clearType() {
      type = null;
      fieldSetFlags()[7] = false;
      return this;
    }

    /** Gets the value of the 'uuid' field */
    public CharSequence getUuid() {
      return uuid;
    }

    /** Sets the value of the 'uuid' field */
    public com.izhengyin.test.other.serial.Events.Builder setUuid(CharSequence value) {
      validate(fields()[8], value);
      this.uuid = value;
      fieldSetFlags()[8] = true;
      return this;
    }

    /** Checks whether the 'uuid' field has been set */
    public boolean hasUuid() {
      return fieldSetFlags()[8];
    }

    /** Clears the value of the 'uuid' field */
    public com.izhengyin.test.other.serial.Events.Builder clearUuid() {
      uuid = null;
      fieldSetFlags()[8] = false;
      return this;
    }

    /** Gets the value of the 'utm_source' field */
    public CharSequence getUtmSource() {
      return utm_source;
    }

    /** Sets the value of the 'utm_source' field */
    public com.izhengyin.test.other.serial.Events.Builder setUtmSource(CharSequence value) {
      validate(fields()[9], value);
      this.utm_source = value;
      fieldSetFlags()[9] = true;
      return this;
    }

    /** Checks whether the 'utm_source' field has been set */
    public boolean hasUtmSource() {
      return fieldSetFlags()[9];
    }

    /** Clears the value of the 'utm_source' field */
    public com.izhengyin.test.other.serial.Events.Builder clearUtmSource() {
      utm_source = null;
      fieldSetFlags()[9] = false;
      return this;
    }

    /** Gets the value of the 'resolution' field */
    public CharSequence getResolution() {
      return resolution;
    }

    /** Sets the value of the 'resolution' field */
    public com.izhengyin.test.other.serial.Events.Builder setResolution(CharSequence value) {
      validate(fields()[10], value);
      this.resolution = value;
      fieldSetFlags()[10] = true;
      return this;
    }

    /** Checks whether the 'resolution' field has been set */
    public boolean hasResolution() {
      return fieldSetFlags()[10];
    }

    /** Clears the value of the 'resolution' field */
    public com.izhengyin.test.other.serial.Events.Builder clearResolution() {
      resolution = null;
      fieldSetFlags()[10] = false;
      return this;
    }

    /** Gets the value of the 'client_ip' field */
    public CharSequence getClientIp() {
      return client_ip;
    }

    /** Sets the value of the 'client_ip' field */
    public com.izhengyin.test.other.serial.Events.Builder setClientIp(CharSequence value) {
      validate(fields()[11], value);
      this.client_ip = value;
      fieldSetFlags()[11] = true;
      return this;
    }

    /** Checks whether the 'client_ip' field has been set */
    public boolean hasClientIp() {
      return fieldSetFlags()[11];
    }

    /** Clears the value of the 'client_ip' field */
    public com.izhengyin.test.other.serial.Events.Builder clearClientIp() {
      client_ip = null;
      fieldSetFlags()[11] = false;
      return this;
    }

    /** Gets the value of the 'user_agent' field */
    public CharSequence getUserAgent() {
      return user_agent;
    }

    /** Sets the value of the 'user_agent' field */
    public com.izhengyin.test.other.serial.Events.Builder setUserAgent(CharSequence value) {
      validate(fields()[12], value);
      this.user_agent = value;
      fieldSetFlags()[12] = true;
      return this;
    }

    /** Checks whether the 'user_agent' field has been set */
    public boolean hasUserAgent() {
      return fieldSetFlags()[12];
    }

    /** Clears the value of the 'user_agent' field */
    public com.izhengyin.test.other.serial.Events.Builder clearUserAgent() {
      user_agent = null;
      fieldSetFlags()[12] = false;
      return this;
    }

    /** Gets the value of the 'country' field */
    public CharSequence getCountry() {
      return country;
    }

    /** Sets the value of the 'country' field */
    public com.izhengyin.test.other.serial.Events.Builder setCountry(CharSequence value) {
      validate(fields()[13], value);
      this.country = value;
      fieldSetFlags()[13] = true;
      return this;
    }

    /** Checks whether the 'country' field has been set */
    public boolean hasCountry() {
      return fieldSetFlags()[13];
    }

    /** Clears the value of the 'country' field */
    public com.izhengyin.test.other.serial.Events.Builder clearCountry() {
      country = null;
      fieldSetFlags()[13] = false;
      return this;
    }

    /** Gets the value of the 'province' field */
    public CharSequence getProvince() {
      return province;
    }

    /** Sets the value of the 'province' field */
    public com.izhengyin.test.other.serial.Events.Builder setProvince(CharSequence value) {
      validate(fields()[14], value);
      this.province = value;
      fieldSetFlags()[14] = true;
      return this;
    }

    /** Checks whether the 'province' field has been set */
    public boolean hasProvince() {
      return fieldSetFlags()[14];
    }

    /** Clears the value of the 'province' field */
    public com.izhengyin.test.other.serial.Events.Builder clearProvince() {
      province = null;
      fieldSetFlags()[14] = false;
      return this;
    }

    /** Gets the value of the 'city' field */
    public CharSequence getCity() {
      return city;
    }

    /** Sets the value of the 'city' field */
    public com.izhengyin.test.other.serial.Events.Builder setCity(CharSequence value) {
      validate(fields()[15], value);
      this.city = value;
      fieldSetFlags()[15] = true;
      return this;
    }

    /** Checks whether the 'city' field has been set */
    public boolean hasCity() {
      return fieldSetFlags()[15];
    }

    /** Clears the value of the 'city' field */
    public com.izhengyin.test.other.serial.Events.Builder clearCity() {
      city = null;
      fieldSetFlags()[15] = false;
      return this;
    }

    /** Gets the value of the 'self_page' field */
    public CharSequence getSelfPage() {
      return self_page;
    }

    /** Sets the value of the 'self_page' field */
    public com.izhengyin.test.other.serial.Events.Builder setSelfPage(CharSequence value) {
      validate(fields()[16], value);
      this.self_page = value;
      fieldSetFlags()[16] = true;
      return this;
    }

    /** Checks whether the 'self_page' field has been set */
    public boolean hasSelfPage() {
      return fieldSetFlags()[16];
    }

    /** Clears the value of the 'self_page' field */
    public com.izhengyin.test.other.serial.Events.Builder clearSelfPage() {
      self_page = null;
      fieldSetFlags()[16] = false;
      return this;
    }

    /** Gets the value of the 'ref_page' field */
    public CharSequence getRefPage() {
      return ref_page;
    }

    /** Sets the value of the 'ref_page' field */
    public com.izhengyin.test.other.serial.Events.Builder setRefPage(CharSequence value) {
      validate(fields()[17], value);
      this.ref_page = value;
      fieldSetFlags()[17] = true;
      return this;
    }

    /** Checks whether the 'ref_page' field has been set */
    public boolean hasRefPage() {
      return fieldSetFlags()[17];
    }

    /** Clears the value of the 'ref_page' field */
    public com.izhengyin.test.other.serial.Events.Builder clearRefPage() {
      ref_page = null;
      fieldSetFlags()[17] = false;
      return this;
    }

    /** Gets the value of the 'session_id' field */
    public CharSequence getSessionId() {
      return session_id;
    }

    /** Sets the value of the 'session_id' field */
    public com.izhengyin.test.other.serial.Events.Builder setSessionId(CharSequence value) {
      validate(fields()[18], value);
      this.session_id = value;
      fieldSetFlags()[18] = true;
      return this;
    }

    /** Checks whether the 'session_id' field has been set */
    public boolean hasSessionId() {
      return fieldSetFlags()[18];
    }

    /** Clears the value of the 'session_id' field */
    public com.izhengyin.test.other.serial.Events.Builder clearSessionId() {
      session_id = null;
      fieldSetFlags()[18] = false;
      return this;
    }

    /** Gets the value of the 'session_duration' field */
    public CharSequence getSessionDuration() {
      return session_duration;
    }

    /** Sets the value of the 'session_duration' field */
    public com.izhengyin.test.other.serial.Events.Builder setSessionDuration(CharSequence value) {
      validate(fields()[19], value);
      this.session_duration = value;
      fieldSetFlags()[19] = true;
      return this;
    }

    /** Checks whether the 'session_duration' field has been set */
    public boolean hasSessionDuration() {
      return fieldSetFlags()[19];
    }

    /** Clears the value of the 'session_duration' field */
    public com.izhengyin.test.other.serial.Events.Builder clearSessionDuration() {
      session_duration = null;
      fieldSetFlags()[19] = false;
      return this;
    }

    /** Gets the value of the 'app_name' field */
    public CharSequence getAppName() {
      return app_name;
    }

    /** Sets the value of the 'app_name' field */
    public com.izhengyin.test.other.serial.Events.Builder setAppName(CharSequence value) {
      validate(fields()[20], value);
      this.app_name = value;
      fieldSetFlags()[20] = true;
      return this;
    }

    /** Checks whether the 'app_name' field has been set */
    public boolean hasAppName() {
      return fieldSetFlags()[20];
    }

    /** Clears the value of the 'app_name' field */
    public com.izhengyin.test.other.serial.Events.Builder clearAppName() {
      app_name = null;
      fieldSetFlags()[20] = false;
      return this;
    }

    /** Gets the value of the 'app_version' field */
    public CharSequence getAppVersion() {
      return app_version;
    }

    /** Sets the value of the 'app_version' field */
    public com.izhengyin.test.other.serial.Events.Builder setAppVersion(CharSequence value) {
      validate(fields()[21], value);
      this.app_version = value;
      fieldSetFlags()[21] = true;
      return this;
    }

    /** Checks whether the 'app_version' field has been set */
    public boolean hasAppVersion() {
      return fieldSetFlags()[21];
    }

    /** Clears the value of the 'app_version' field */
    public com.izhengyin.test.other.serial.Events.Builder clearAppVersion() {
      app_version = null;
      fieldSetFlags()[21] = false;
      return this;
    }

    /** Gets the value of the 'event_date' field */
    public CharSequence getEventDate() {
      return event_date;
    }

    /** Sets the value of the 'event_date' field */
    public com.izhengyin.test.other.serial.Events.Builder setEventDate(CharSequence value) {
      validate(fields()[22], value);
      this.event_date = value;
      fieldSetFlags()[22] = true;
      return this;
    }

    /** Checks whether the 'event_date' field has been set */
    public boolean hasEventDate() {
      return fieldSetFlags()[22];
    }

    /** Clears the value of the 'event_date' field */
    public com.izhengyin.test.other.serial.Events.Builder clearEventDate() {
      event_date = null;
      fieldSetFlags()[22] = false;
      return this;
    }

    /** Gets the value of the 'event_time' field */
    public Long getEventTime() {
      return event_time;
    }

    /** Sets the value of the 'event_time' field */
    public com.izhengyin.test.other.serial.Events.Builder setEventTime(long value) {
      validate(fields()[23], value);
      this.event_time = value;
      fieldSetFlags()[23] = true;
      return this;
    }

    /** Checks whether the 'event_time' field has been set */
    public boolean hasEventTime() {
      return fieldSetFlags()[23];
    }

    /** Clears the value of the 'event_time' field */
    public com.izhengyin.test.other.serial.Events.Builder clearEventTime() {
      fieldSetFlags()[23] = false;
      return this;
    }

    /** Gets the value of the 'event_time_ms' field */
    public Long getEventTimeMs() {
      return event_time_ms;
    }

    /** Sets the value of the 'event_time_ms' field */
    public com.izhengyin.test.other.serial.Events.Builder setEventTimeMs(long value) {
      validate(fields()[24], value);
      this.event_time_ms = value;
      fieldSetFlags()[24] = true;
      return this;
    }

    /** Checks whether the 'event_time_ms' field has been set */
    public boolean hasEventTimeMs() {
      return fieldSetFlags()[24];
    }

    /** Clears the value of the 'event_time_ms' field */
    public com.izhengyin.test.other.serial.Events.Builder clearEventTimeMs() {
      fieldSetFlags()[24] = false;
      return this;
    }

    /** Gets the value of the 'platform_attr' field */
    public java.util.Map<CharSequence,CharSequence> getPlatformAttr() {
      return platform_attr;
    }

    /** Sets the value of the 'platform_attr' field */
    public com.izhengyin.test.other.serial.Events.Builder setPlatformAttr(java.util.Map<CharSequence,CharSequence> value) {
      validate(fields()[25], value);
      this.platform_attr = value;
      fieldSetFlags()[25] = true;
      return this;
    }

    /** Checks whether the 'platform_attr' field has been set */
    public boolean hasPlatformAttr() {
      return fieldSetFlags()[25];
    }

    /** Clears the value of the 'platform_attr' field */
    public com.izhengyin.test.other.serial.Events.Builder clearPlatformAttr() {
      platform_attr = null;
      fieldSetFlags()[25] = false;
      return this;
    }

    /** Gets the value of the 'count_attr' field */
    public java.util.Map<CharSequence,Integer> getCountAttr() {
      return count_attr;
    }

    /** Sets the value of the 'count_attr' field */
    public com.izhengyin.test.other.serial.Events.Builder setCountAttr(java.util.Map<CharSequence,Integer> value) {
      validate(fields()[26], value);
      this.count_attr = value;
      fieldSetFlags()[26] = true;
      return this;
    }

    /** Checks whether the 'count_attr' field has been set */
    public boolean hasCountAttr() {
      return fieldSetFlags()[26];
    }

    /** Clears the value of the 'count_attr' field */
    public com.izhengyin.test.other.serial.Events.Builder clearCountAttr() {
      count_attr = null;
      fieldSetFlags()[26] = false;
      return this;
    }

    /** Gets the value of the 'event_attr' field */
    public java.util.Map<CharSequence,CharSequence> getEventAttr() {
      return event_attr;
    }

    /** Sets the value of the 'event_attr' field */
    public com.izhengyin.test.other.serial.Events.Builder setEventAttr(java.util.Map<CharSequence,CharSequence> value) {
      validate(fields()[27], value);
      this.event_attr = value;
      fieldSetFlags()[27] = true;
      return this;
    }

    /** Checks whether the 'event_attr' field has been set */
    public boolean hasEventAttr() {
      return fieldSetFlags()[27];
    }

    /** Clears the value of the 'event_attr' field */
    public com.izhengyin.test.other.serial.Events.Builder clearEventAttr() {
      event_attr = null;
      fieldSetFlags()[27] = false;
      return this;
    }

    public Events build() {
      try {
        Events record = new Events();
        record.id = fieldSetFlags()[0] ? this.id : (Long) defaultValue(fields()[0]);
        record.event = fieldSetFlags()[1] ? this.event : (CharSequence) defaultValue(fields()[1]);
        record.platform = fieldSetFlags()[2] ? this.platform : (CharSequence) defaultValue(fields()[2]);
        record.client = fieldSetFlags()[3] ? this.client : (CharSequence) defaultValue(fields()[3]);
        record.shop_id = fieldSetFlags()[4] ? this.shop_id : (Integer) defaultValue(fields()[4]);
        record.user_id = fieldSetFlags()[5] ? this.user_id : (Integer) defaultValue(fields()[5]);
        record.seller_id = fieldSetFlags()[6] ? this.seller_id : (Integer) defaultValue(fields()[6]);
        record.type = fieldSetFlags()[7] ? this.type : (CharSequence) defaultValue(fields()[7]);
        record.uuid = fieldSetFlags()[8] ? this.uuid : (CharSequence) defaultValue(fields()[8]);
        record.utm_source = fieldSetFlags()[9] ? this.utm_source : (CharSequence) defaultValue(fields()[9]);
        record.resolution = fieldSetFlags()[10] ? this.resolution : (CharSequence) defaultValue(fields()[10]);
        record.client_ip = fieldSetFlags()[11] ? this.client_ip : (CharSequence) defaultValue(fields()[11]);
        record.user_agent = fieldSetFlags()[12] ? this.user_agent : (CharSequence) defaultValue(fields()[12]);
        record.country = fieldSetFlags()[13] ? this.country : (CharSequence) defaultValue(fields()[13]);
        record.province = fieldSetFlags()[14] ? this.province : (CharSequence) defaultValue(fields()[14]);
        record.city = fieldSetFlags()[15] ? this.city : (CharSequence) defaultValue(fields()[15]);
        record.self_page = fieldSetFlags()[16] ? this.self_page : (CharSequence) defaultValue(fields()[16]);
        record.ref_page = fieldSetFlags()[17] ? this.ref_page : (CharSequence) defaultValue(fields()[17]);
        record.session_id = fieldSetFlags()[18] ? this.session_id : (CharSequence) defaultValue(fields()[18]);
        record.session_duration = fieldSetFlags()[19] ? this.session_duration : (CharSequence) defaultValue(fields()[19]);
        record.app_name = fieldSetFlags()[20] ? this.app_name : (CharSequence) defaultValue(fields()[20]);
        record.app_version = fieldSetFlags()[21] ? this.app_version : (CharSequence) defaultValue(fields()[21]);
        record.event_date = fieldSetFlags()[22] ? this.event_date : (CharSequence) defaultValue(fields()[22]);
        record.event_time = fieldSetFlags()[23] ? this.event_time : (Long) defaultValue(fields()[23]);
        record.event_time_ms = fieldSetFlags()[24] ? this.event_time_ms : (Long) defaultValue(fields()[24]);
        record.platform_attr = fieldSetFlags()[25] ? this.platform_attr : (java.util.Map<CharSequence,CharSequence>) defaultValue(fields()[25]);
        record.count_attr = fieldSetFlags()[26] ? this.count_attr : (java.util.Map<CharSequence,Integer>) defaultValue(fields()[26]);
        record.event_attr = fieldSetFlags()[27] ? this.event_attr : (java.util.Map<CharSequence,CharSequence>) defaultValue(fields()[27]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
