+---------------------------------------------------------------------+--+
|                           createtab_stmt                            |
+---------------------------------------------------------------------+--+
| CREATE EXTERNAL TABLE `test_parquet`(                               |
|   `stringvar` string COMMENT '',                                    |
|   `bytesvar` binary COMMENT '',                                     |
|   `booleanvar` boolean COMMENT '',                                  |
|   `intvar` int COMMENT '',                                          |
|   `longvar` bigint COMMENT '',                                      |
|   `floatvar` float COMMENT '',                                      |
|   `doublevar` double COMMENT '',                                    |
|   `enumvar` string COMMENT '',                                      |
|   `strarrayvar` array<string> COMMENT '',                           |
|   `intarrayvar` array<int> COMMENT '',                              |
|   `mapvar` map<string,bigint> COMMENT '',                           |
|   `fixedvar` binary COMMENT '')                                     |
| ROW FORMAT SERDE                                                    |
|   'org.apache.hadoop.hive.ql.io.parquet.serde.ParquetHiveSerDe'     |
| STORED AS INPUTFORMAT                                               |
|   'org.apache.hadoop.hive.ql.io.parquet.MapredParquetInputFormat'   |
| OUTPUTFORMAT                                                        |
|   'org.apache.hadoop.hive.ql.io.parquet.MapredParquetOutputFormat'  |
| LOCATION                                                            |
|   'hdfs://kongfz/user/hive/warehouse/test_parquet'                  |
| TBLPROPERTIES (                                                     |
|   'COLUMN_STATS_ACCURATE'='false',                                  |
|   'numFiles'='0',                                                   |
|   'numRows'='-1',                                                   |
|   'rawDataSize'='-1',                                               |
|   'totalSize'='0',                                                  |
|   'transient_lastDdlTime'='1528698990')                             |
+---------------------------------------------------------------------+--+