/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.demo.hadoop.avro;  
@SuppressWarnings("all")
/** http://gitbook.kongfz.com */
@org.apache.avro.specific.AvroGenerated
public class Event extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Event\",\"namespace\":\"com.demo.hadoop.avro\",\"doc\":\"http://gitbook.kongfz.com\",\"fields\":[{\"name\":\"event\",\"type\":\"string\"},{\"name\":\"userid\",\"type\":\"int\"},{\"name\":\"uuid\",\"type\":\"string\"},{\"name\":\"ip\",\"type\":\"string\"},{\"name\":\"s_channel\",\"type\":\"string\"},{\"name\":\"self_url\",\"type\":\"string\"},{\"name\":\"ref_url\",\"type\":\"string\",\"default\":\"\"},{\"name\":\"app_name\",\"type\":\"string\"},{\"name\":\"platform\",\"type\":\"string\"},{\"name\":\"event_date\",\"type\":\"string\"},{\"name\":\"event_time\",\"type\":\"int\"},{\"name\":\"event_attr\",\"type\":{\"type\":\"map\",\"values\":\"string\"}},{\"name\":\"event_string_args\",\"type\":{\"type\":\"map\",\"values\":\"string\"},\"default\":null},{\"name\":\"event_double_args\",\"type\":{\"type\":\"map\",\"values\":\"double\"},\"default\":null},{\"name\":\"attach_fields_1\",\"type\":\"int\",\"default\":0},{\"name\":\"attach_fields_2\",\"type\":\"string\",\"default\":\"\"},{\"name\":\"attach_fields_3\",\"type\":{\"type\":\"map\",\"values\":\"string\"},\"default\":null},{\"name\":\"attach_fields_4\",\"type\":{\"type\":\"map\",\"values\":\"int\"},\"default\":null}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.CharSequence event;
  @Deprecated public int userid;
  @Deprecated public java.lang.CharSequence uuid;
  @Deprecated public java.lang.CharSequence ip;
  @Deprecated public java.lang.CharSequence s_channel;
  @Deprecated public java.lang.CharSequence self_url;
  @Deprecated public java.lang.CharSequence ref_url;
  @Deprecated public java.lang.CharSequence app_name;
  @Deprecated public java.lang.CharSequence platform;
  @Deprecated public java.lang.CharSequence event_date;
  @Deprecated public int event_time;
  @Deprecated public java.util.Map<java.lang.CharSequence,java.lang.CharSequence> event_attr;
  @Deprecated public java.util.Map<java.lang.CharSequence,java.lang.CharSequence> event_string_args;
  @Deprecated public java.util.Map<java.lang.CharSequence,java.lang.Double> event_double_args;
  @Deprecated public int attach_fields_1;
  @Deprecated public java.lang.CharSequence attach_fields_2;
  @Deprecated public java.util.Map<java.lang.CharSequence,java.lang.CharSequence> attach_fields_3;
  @Deprecated public java.util.Map<java.lang.CharSequence,java.lang.Integer> attach_fields_4;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use {@link \#newBuilder()}. 
   */
  public Event() {}

  /**
   * All-args constructor.
   */
  public Event(java.lang.CharSequence event, java.lang.Integer userid, java.lang.CharSequence uuid, java.lang.CharSequence ip, java.lang.CharSequence s_channel, java.lang.CharSequence self_url, java.lang.CharSequence ref_url, java.lang.CharSequence app_name, java.lang.CharSequence platform, java.lang.CharSequence event_date, java.lang.Integer event_time, java.util.Map<java.lang.CharSequence,java.lang.CharSequence> event_attr, java.util.Map<java.lang.CharSequence,java.lang.CharSequence> event_string_args, java.util.Map<java.lang.CharSequence,java.lang.Double> event_double_args, java.lang.Integer attach_fields_1, java.lang.CharSequence attach_fields_2, java.util.Map<java.lang.CharSequence,java.lang.CharSequence> attach_fields_3, java.util.Map<java.lang.CharSequence,java.lang.Integer> attach_fields_4) {
    this.event = event;
    this.userid = userid;
    this.uuid = uuid;
    this.ip = ip;
    this.s_channel = s_channel;
    this.self_url = self_url;
    this.ref_url = ref_url;
    this.app_name = app_name;
    this.platform = platform;
    this.event_date = event_date;
    this.event_time = event_time;
    this.event_attr = event_attr;
    this.event_string_args = event_string_args;
    this.event_double_args = event_double_args;
    this.attach_fields_1 = attach_fields_1;
    this.attach_fields_2 = attach_fields_2;
    this.attach_fields_3 = attach_fields_3;
    this.attach_fields_4 = attach_fields_4;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return event;
    case 1: return userid;
    case 2: return uuid;
    case 3: return ip;
    case 4: return s_channel;
    case 5: return self_url;
    case 6: return ref_url;
    case 7: return app_name;
    case 8: return platform;
    case 9: return event_date;
    case 10: return event_time;
    case 11: return event_attr;
    case 12: return event_string_args;
    case 13: return event_double_args;
    case 14: return attach_fields_1;
    case 15: return attach_fields_2;
    case 16: return attach_fields_3;
    case 17: return attach_fields_4;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: event = (java.lang.CharSequence)value$; break;
    case 1: userid = (java.lang.Integer)value$; break;
    case 2: uuid = (java.lang.CharSequence)value$; break;
    case 3: ip = (java.lang.CharSequence)value$; break;
    case 4: s_channel = (java.lang.CharSequence)value$; break;
    case 5: self_url = (java.lang.CharSequence)value$; break;
    case 6: ref_url = (java.lang.CharSequence)value$; break;
    case 7: app_name = (java.lang.CharSequence)value$; break;
    case 8: platform = (java.lang.CharSequence)value$; break;
    case 9: event_date = (java.lang.CharSequence)value$; break;
    case 10: event_time = (java.lang.Integer)value$; break;
    case 11: event_attr = (java.util.Map<java.lang.CharSequence,java.lang.CharSequence>)value$; break;
    case 12: event_string_args = (java.util.Map<java.lang.CharSequence,java.lang.CharSequence>)value$; break;
    case 13: event_double_args = (java.util.Map<java.lang.CharSequence,java.lang.Double>)value$; break;
    case 14: attach_fields_1 = (java.lang.Integer)value$; break;
    case 15: attach_fields_2 = (java.lang.CharSequence)value$; break;
    case 16: attach_fields_3 = (java.util.Map<java.lang.CharSequence,java.lang.CharSequence>)value$; break;
    case 17: attach_fields_4 = (java.util.Map<java.lang.CharSequence,java.lang.Integer>)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'event' field.
   */
  public java.lang.CharSequence getEvent() {
    return event;
  }

  /**
   * Sets the value of the 'event' field.
   * @param value the value to set.
   */
  public void setEvent(java.lang.CharSequence value) {
    this.event = value;
  }

  /**
   * Gets the value of the 'userid' field.
   */
  public java.lang.Integer getUserid() {
    return userid;
  }

  /**
   * Sets the value of the 'userid' field.
   * @param value the value to set.
   */
  public void setUserid(java.lang.Integer value) {
    this.userid = value;
  }

  /**
   * Gets the value of the 'uuid' field.
   */
  public java.lang.CharSequence getUuid() {
    return uuid;
  }

  /**
   * Sets the value of the 'uuid' field.
   * @param value the value to set.
   */
  public void setUuid(java.lang.CharSequence value) {
    this.uuid = value;
  }

  /**
   * Gets the value of the 'ip' field.
   */
  public java.lang.CharSequence getIp() {
    return ip;
  }

  /**
   * Sets the value of the 'ip' field.
   * @param value the value to set.
   */
  public void setIp(java.lang.CharSequence value) {
    this.ip = value;
  }

  /**
   * Gets the value of the 's_channel' field.
   */
  public java.lang.CharSequence getSChannel() {
    return s_channel;
  }

  /**
   * Sets the value of the 's_channel' field.
   * @param value the value to set.
   */
  public void setSChannel(java.lang.CharSequence value) {
    this.s_channel = value;
  }

  /**
   * Gets the value of the 'self_url' field.
   */
  public java.lang.CharSequence getSelfUrl() {
    return self_url;
  }

  /**
   * Sets the value of the 'self_url' field.
   * @param value the value to set.
   */
  public void setSelfUrl(java.lang.CharSequence value) {
    this.self_url = value;
  }

  /**
   * Gets the value of the 'ref_url' field.
   */
  public java.lang.CharSequence getRefUrl() {
    return ref_url;
  }

  /**
   * Sets the value of the 'ref_url' field.
   * @param value the value to set.
   */
  public void setRefUrl(java.lang.CharSequence value) {
    this.ref_url = value;
  }

  /**
   * Gets the value of the 'app_name' field.
   */
  public java.lang.CharSequence getAppName() {
    return app_name;
  }

  /**
   * Sets the value of the 'app_name' field.
   * @param value the value to set.
   */
  public void setAppName(java.lang.CharSequence value) {
    this.app_name = value;
  }

  /**
   * Gets the value of the 'platform' field.
   */
  public java.lang.CharSequence getPlatform() {
    return platform;
  }

  /**
   * Sets the value of the 'platform' field.
   * @param value the value to set.
   */
  public void setPlatform(java.lang.CharSequence value) {
    this.platform = value;
  }

  /**
   * Gets the value of the 'event_date' field.
   */
  public java.lang.CharSequence getEventDate() {
    return event_date;
  }

  /**
   * Sets the value of the 'event_date' field.
   * @param value the value to set.
   */
  public void setEventDate(java.lang.CharSequence value) {
    this.event_date = value;
  }

  /**
   * Gets the value of the 'event_time' field.
   */
  public java.lang.Integer getEventTime() {
    return event_time;
  }

  /**
   * Sets the value of the 'event_time' field.
   * @param value the value to set.
   */
  public void setEventTime(java.lang.Integer value) {
    this.event_time = value;
  }

  /**
   * Gets the value of the 'event_attr' field.
   */
  public java.util.Map<java.lang.CharSequence,java.lang.CharSequence> getEventAttr() {
    return event_attr;
  }

  /**
   * Sets the value of the 'event_attr' field.
   * @param value the value to set.
   */
  public void setEventAttr(java.util.Map<java.lang.CharSequence,java.lang.CharSequence> value) {
    this.event_attr = value;
  }

  /**
   * Gets the value of the 'event_string_args' field.
   */
  public java.util.Map<java.lang.CharSequence,java.lang.CharSequence> getEventStringArgs() {
    return event_string_args;
  }

  /**
   * Sets the value of the 'event_string_args' field.
   * @param value the value to set.
   */
  public void setEventStringArgs(java.util.Map<java.lang.CharSequence,java.lang.CharSequence> value) {
    this.event_string_args = value;
  }

  /**
   * Gets the value of the 'event_double_args' field.
   */
  public java.util.Map<java.lang.CharSequence,java.lang.Double> getEventDoubleArgs() {
    return event_double_args;
  }

  /**
   * Sets the value of the 'event_double_args' field.
   * @param value the value to set.
   */
  public void setEventDoubleArgs(java.util.Map<java.lang.CharSequence,java.lang.Double> value) {
    this.event_double_args = value;
  }

  /**
   * Gets the value of the 'attach_fields_1' field.
   */
  public java.lang.Integer getAttachFields1() {
    return attach_fields_1;
  }

  /**
   * Sets the value of the 'attach_fields_1' field.
   * @param value the value to set.
   */
  public void setAttachFields1(java.lang.Integer value) {
    this.attach_fields_1 = value;
  }

  /**
   * Gets the value of the 'attach_fields_2' field.
   */
  public java.lang.CharSequence getAttachFields2() {
    return attach_fields_2;
  }

  /**
   * Sets the value of the 'attach_fields_2' field.
   * @param value the value to set.
   */
  public void setAttachFields2(java.lang.CharSequence value) {
    this.attach_fields_2 = value;
  }

  /**
   * Gets the value of the 'attach_fields_3' field.
   */
  public java.util.Map<java.lang.CharSequence,java.lang.CharSequence> getAttachFields3() {
    return attach_fields_3;
  }

  /**
   * Sets the value of the 'attach_fields_3' field.
   * @param value the value to set.
   */
  public void setAttachFields3(java.util.Map<java.lang.CharSequence,java.lang.CharSequence> value) {
    this.attach_fields_3 = value;
  }

  /**
   * Gets the value of the 'attach_fields_4' field.
   */
  public java.util.Map<java.lang.CharSequence,java.lang.Integer> getAttachFields4() {
    return attach_fields_4;
  }

  /**
   * Sets the value of the 'attach_fields_4' field.
   * @param value the value to set.
   */
  public void setAttachFields4(java.util.Map<java.lang.CharSequence,java.lang.Integer> value) {
    this.attach_fields_4 = value;
  }

  /** Creates a new Event RecordBuilder */
  public static com.demo.hadoop.avro.Event.Builder newBuilder() {
    return new com.demo.hadoop.avro.Event.Builder();
  }
  
  /** Creates a new Event RecordBuilder by copying an existing Builder */
  public static com.demo.hadoop.avro.Event.Builder newBuilder(com.demo.hadoop.avro.Event.Builder other) {
    return new com.demo.hadoop.avro.Event.Builder(other);
  }
  
  /** Creates a new Event RecordBuilder by copying an existing Event instance */
  public static com.demo.hadoop.avro.Event.Builder newBuilder(com.demo.hadoop.avro.Event other) {
    return new com.demo.hadoop.avro.Event.Builder(other);
  }
  
  /**
   * RecordBuilder for Event instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Event>
    implements org.apache.avro.data.RecordBuilder<Event> {

    private java.lang.CharSequence event;
    private int userid;
    private java.lang.CharSequence uuid;
    private java.lang.CharSequence ip;
    private java.lang.CharSequence s_channel;
    private java.lang.CharSequence self_url;
    private java.lang.CharSequence ref_url;
    private java.lang.CharSequence app_name;
    private java.lang.CharSequence platform;
    private java.lang.CharSequence event_date;
    private int event_time;
    private java.util.Map<java.lang.CharSequence,java.lang.CharSequence> event_attr;
    private java.util.Map<java.lang.CharSequence,java.lang.CharSequence> event_string_args;
    private java.util.Map<java.lang.CharSequence,java.lang.Double> event_double_args;
    private int attach_fields_1;
    private java.lang.CharSequence attach_fields_2;
    private java.util.Map<java.lang.CharSequence,java.lang.CharSequence> attach_fields_3;
    private java.util.Map<java.lang.CharSequence,java.lang.Integer> attach_fields_4;

    /** Creates a new Builder */
    private Builder() {
      super(com.demo.hadoop.avro.Event.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(com.demo.hadoop.avro.Event.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.event)) {
        this.event = data().deepCopy(fields()[0].schema(), other.event);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.userid)) {
        this.userid = data().deepCopy(fields()[1].schema(), other.userid);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.uuid)) {
        this.uuid = data().deepCopy(fields()[2].schema(), other.uuid);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.ip)) {
        this.ip = data().deepCopy(fields()[3].schema(), other.ip);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.s_channel)) {
        this.s_channel = data().deepCopy(fields()[4].schema(), other.s_channel);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.self_url)) {
        this.self_url = data().deepCopy(fields()[5].schema(), other.self_url);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.ref_url)) {
        this.ref_url = data().deepCopy(fields()[6].schema(), other.ref_url);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.app_name)) {
        this.app_name = data().deepCopy(fields()[7].schema(), other.app_name);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.platform)) {
        this.platform = data().deepCopy(fields()[8].schema(), other.platform);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.event_date)) {
        this.event_date = data().deepCopy(fields()[9].schema(), other.event_date);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.event_time)) {
        this.event_time = data().deepCopy(fields()[10].schema(), other.event_time);
        fieldSetFlags()[10] = true;
      }
      if (isValidValue(fields()[11], other.event_attr)) {
        this.event_attr = data().deepCopy(fields()[11].schema(), other.event_attr);
        fieldSetFlags()[11] = true;
      }
      if (isValidValue(fields()[12], other.event_string_args)) {
        this.event_string_args = data().deepCopy(fields()[12].schema(), other.event_string_args);
        fieldSetFlags()[12] = true;
      }
      if (isValidValue(fields()[13], other.event_double_args)) {
        this.event_double_args = data().deepCopy(fields()[13].schema(), other.event_double_args);
        fieldSetFlags()[13] = true;
      }
      if (isValidValue(fields()[14], other.attach_fields_1)) {
        this.attach_fields_1 = data().deepCopy(fields()[14].schema(), other.attach_fields_1);
        fieldSetFlags()[14] = true;
      }
      if (isValidValue(fields()[15], other.attach_fields_2)) {
        this.attach_fields_2 = data().deepCopy(fields()[15].schema(), other.attach_fields_2);
        fieldSetFlags()[15] = true;
      }
      if (isValidValue(fields()[16], other.attach_fields_3)) {
        this.attach_fields_3 = data().deepCopy(fields()[16].schema(), other.attach_fields_3);
        fieldSetFlags()[16] = true;
      }
      if (isValidValue(fields()[17], other.attach_fields_4)) {
        this.attach_fields_4 = data().deepCopy(fields()[17].schema(), other.attach_fields_4);
        fieldSetFlags()[17] = true;
      }
    }
    
    /** Creates a Builder by copying an existing Event instance */
    private Builder(com.demo.hadoop.avro.Event other) {
            super(com.demo.hadoop.avro.Event.SCHEMA$);
      if (isValidValue(fields()[0], other.event)) {
        this.event = data().deepCopy(fields()[0].schema(), other.event);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.userid)) {
        this.userid = data().deepCopy(fields()[1].schema(), other.userid);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.uuid)) {
        this.uuid = data().deepCopy(fields()[2].schema(), other.uuid);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.ip)) {
        this.ip = data().deepCopy(fields()[3].schema(), other.ip);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.s_channel)) {
        this.s_channel = data().deepCopy(fields()[4].schema(), other.s_channel);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.self_url)) {
        this.self_url = data().deepCopy(fields()[5].schema(), other.self_url);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.ref_url)) {
        this.ref_url = data().deepCopy(fields()[6].schema(), other.ref_url);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.app_name)) {
        this.app_name = data().deepCopy(fields()[7].schema(), other.app_name);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.platform)) {
        this.platform = data().deepCopy(fields()[8].schema(), other.platform);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.event_date)) {
        this.event_date = data().deepCopy(fields()[9].schema(), other.event_date);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.event_time)) {
        this.event_time = data().deepCopy(fields()[10].schema(), other.event_time);
        fieldSetFlags()[10] = true;
      }
      if (isValidValue(fields()[11], other.event_attr)) {
        this.event_attr = data().deepCopy(fields()[11].schema(), other.event_attr);
        fieldSetFlags()[11] = true;
      }
      if (isValidValue(fields()[12], other.event_string_args)) {
        this.event_string_args = data().deepCopy(fields()[12].schema(), other.event_string_args);
        fieldSetFlags()[12] = true;
      }
      if (isValidValue(fields()[13], other.event_double_args)) {
        this.event_double_args = data().deepCopy(fields()[13].schema(), other.event_double_args);
        fieldSetFlags()[13] = true;
      }
      if (isValidValue(fields()[14], other.attach_fields_1)) {
        this.attach_fields_1 = data().deepCopy(fields()[14].schema(), other.attach_fields_1);
        fieldSetFlags()[14] = true;
      }
      if (isValidValue(fields()[15], other.attach_fields_2)) {
        this.attach_fields_2 = data().deepCopy(fields()[15].schema(), other.attach_fields_2);
        fieldSetFlags()[15] = true;
      }
      if (isValidValue(fields()[16], other.attach_fields_3)) {
        this.attach_fields_3 = data().deepCopy(fields()[16].schema(), other.attach_fields_3);
        fieldSetFlags()[16] = true;
      }
      if (isValidValue(fields()[17], other.attach_fields_4)) {
        this.attach_fields_4 = data().deepCopy(fields()[17].schema(), other.attach_fields_4);
        fieldSetFlags()[17] = true;
      }
    }

    /** Gets the value of the 'event' field */
    public java.lang.CharSequence getEvent() {
      return event;
    }
    
    /** Sets the value of the 'event' field */
    public com.demo.hadoop.avro.Event.Builder setEvent(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.event = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'event' field has been set */
    public boolean hasEvent() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'event' field */
    public com.demo.hadoop.avro.Event.Builder clearEvent() {
      event = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'userid' field */
    public java.lang.Integer getUserid() {
      return userid;
    }
    
    /** Sets the value of the 'userid' field */
    public com.demo.hadoop.avro.Event.Builder setUserid(int value) {
      validate(fields()[1], value);
      this.userid = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'userid' field has been set */
    public boolean hasUserid() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'userid' field */
    public com.demo.hadoop.avro.Event.Builder clearUserid() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /** Gets the value of the 'uuid' field */
    public java.lang.CharSequence getUuid() {
      return uuid;
    }
    
    /** Sets the value of the 'uuid' field */
    public com.demo.hadoop.avro.Event.Builder setUuid(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.uuid = value;
      fieldSetFlags()[2] = true;
      return this; 
    }
    
    /** Checks whether the 'uuid' field has been set */
    public boolean hasUuid() {
      return fieldSetFlags()[2];
    }
    
    /** Clears the value of the 'uuid' field */
    public com.demo.hadoop.avro.Event.Builder clearUuid() {
      uuid = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /** Gets the value of the 'ip' field */
    public java.lang.CharSequence getIp() {
      return ip;
    }
    
    /** Sets the value of the 'ip' field */
    public com.demo.hadoop.avro.Event.Builder setIp(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.ip = value;
      fieldSetFlags()[3] = true;
      return this; 
    }
    
    /** Checks whether the 'ip' field has been set */
    public boolean hasIp() {
      return fieldSetFlags()[3];
    }
    
    /** Clears the value of the 'ip' field */
    public com.demo.hadoop.avro.Event.Builder clearIp() {
      ip = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /** Gets the value of the 's_channel' field */
    public java.lang.CharSequence getSChannel() {
      return s_channel;
    }
    
    /** Sets the value of the 's_channel' field */
    public com.demo.hadoop.avro.Event.Builder setSChannel(java.lang.CharSequence value) {
      validate(fields()[4], value);
      this.s_channel = value;
      fieldSetFlags()[4] = true;
      return this; 
    }
    
    /** Checks whether the 's_channel' field has been set */
    public boolean hasSChannel() {
      return fieldSetFlags()[4];
    }
    
    /** Clears the value of the 's_channel' field */
    public com.demo.hadoop.avro.Event.Builder clearSChannel() {
      s_channel = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /** Gets the value of the 'self_url' field */
    public java.lang.CharSequence getSelfUrl() {
      return self_url;
    }
    
    /** Sets the value of the 'self_url' field */
    public com.demo.hadoop.avro.Event.Builder setSelfUrl(java.lang.CharSequence value) {
      validate(fields()[5], value);
      this.self_url = value;
      fieldSetFlags()[5] = true;
      return this; 
    }
    
    /** Checks whether the 'self_url' field has been set */
    public boolean hasSelfUrl() {
      return fieldSetFlags()[5];
    }
    
    /** Clears the value of the 'self_url' field */
    public com.demo.hadoop.avro.Event.Builder clearSelfUrl() {
      self_url = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /** Gets the value of the 'ref_url' field */
    public java.lang.CharSequence getRefUrl() {
      return ref_url;
    }
    
    /** Sets the value of the 'ref_url' field */
    public com.demo.hadoop.avro.Event.Builder setRefUrl(java.lang.CharSequence value) {
      validate(fields()[6], value);
      this.ref_url = value;
      fieldSetFlags()[6] = true;
      return this; 
    }
    
    /** Checks whether the 'ref_url' field has been set */
    public boolean hasRefUrl() {
      return fieldSetFlags()[6];
    }
    
    /** Clears the value of the 'ref_url' field */
    public com.demo.hadoop.avro.Event.Builder clearRefUrl() {
      ref_url = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    /** Gets the value of the 'app_name' field */
    public java.lang.CharSequence getAppName() {
      return app_name;
    }
    
    /** Sets the value of the 'app_name' field */
    public com.demo.hadoop.avro.Event.Builder setAppName(java.lang.CharSequence value) {
      validate(fields()[7], value);
      this.app_name = value;
      fieldSetFlags()[7] = true;
      return this; 
    }
    
    /** Checks whether the 'app_name' field has been set */
    public boolean hasAppName() {
      return fieldSetFlags()[7];
    }
    
    /** Clears the value of the 'app_name' field */
    public com.demo.hadoop.avro.Event.Builder clearAppName() {
      app_name = null;
      fieldSetFlags()[7] = false;
      return this;
    }

    /** Gets the value of the 'platform' field */
    public java.lang.CharSequence getPlatform() {
      return platform;
    }
    
    /** Sets the value of the 'platform' field */
    public com.demo.hadoop.avro.Event.Builder setPlatform(java.lang.CharSequence value) {
      validate(fields()[8], value);
      this.platform = value;
      fieldSetFlags()[8] = true;
      return this; 
    }
    
    /** Checks whether the 'platform' field has been set */
    public boolean hasPlatform() {
      return fieldSetFlags()[8];
    }
    
    /** Clears the value of the 'platform' field */
    public com.demo.hadoop.avro.Event.Builder clearPlatform() {
      platform = null;
      fieldSetFlags()[8] = false;
      return this;
    }

    /** Gets the value of the 'event_date' field */
    public java.lang.CharSequence getEventDate() {
      return event_date;
    }
    
    /** Sets the value of the 'event_date' field */
    public com.demo.hadoop.avro.Event.Builder setEventDate(java.lang.CharSequence value) {
      validate(fields()[9], value);
      this.event_date = value;
      fieldSetFlags()[9] = true;
      return this; 
    }
    
    /** Checks whether the 'event_date' field has been set */
    public boolean hasEventDate() {
      return fieldSetFlags()[9];
    }
    
    /** Clears the value of the 'event_date' field */
    public com.demo.hadoop.avro.Event.Builder clearEventDate() {
      event_date = null;
      fieldSetFlags()[9] = false;
      return this;
    }

    /** Gets the value of the 'event_time' field */
    public java.lang.Integer getEventTime() {
      return event_time;
    }
    
    /** Sets the value of the 'event_time' field */
    public com.demo.hadoop.avro.Event.Builder setEventTime(int value) {
      validate(fields()[10], value);
      this.event_time = value;
      fieldSetFlags()[10] = true;
      return this; 
    }
    
    /** Checks whether the 'event_time' field has been set */
    public boolean hasEventTime() {
      return fieldSetFlags()[10];
    }
    
    /** Clears the value of the 'event_time' field */
    public com.demo.hadoop.avro.Event.Builder clearEventTime() {
      fieldSetFlags()[10] = false;
      return this;
    }

    /** Gets the value of the 'event_attr' field */
    public java.util.Map<java.lang.CharSequence,java.lang.CharSequence> getEventAttr() {
      return event_attr;
    }
    
    /** Sets the value of the 'event_attr' field */
    public com.demo.hadoop.avro.Event.Builder setEventAttr(java.util.Map<java.lang.CharSequence,java.lang.CharSequence> value) {
      validate(fields()[11], value);
      this.event_attr = value;
      fieldSetFlags()[11] = true;
      return this; 
    }
    
    /** Checks whether the 'event_attr' field has been set */
    public boolean hasEventAttr() {
      return fieldSetFlags()[11];
    }
    
    /** Clears the value of the 'event_attr' field */
    public com.demo.hadoop.avro.Event.Builder clearEventAttr() {
      event_attr = null;
      fieldSetFlags()[11] = false;
      return this;
    }

    /** Gets the value of the 'event_string_args' field */
    public java.util.Map<java.lang.CharSequence,java.lang.CharSequence> getEventStringArgs() {
      return event_string_args;
    }
    
    /** Sets the value of the 'event_string_args' field */
    public com.demo.hadoop.avro.Event.Builder setEventStringArgs(java.util.Map<java.lang.CharSequence,java.lang.CharSequence> value) {
      validate(fields()[12], value);
      this.event_string_args = value;
      fieldSetFlags()[12] = true;
      return this; 
    }
    
    /** Checks whether the 'event_string_args' field has been set */
    public boolean hasEventStringArgs() {
      return fieldSetFlags()[12];
    }
    
    /** Clears the value of the 'event_string_args' field */
    public com.demo.hadoop.avro.Event.Builder clearEventStringArgs() {
      event_string_args = null;
      fieldSetFlags()[12] = false;
      return this;
    }

    /** Gets the value of the 'event_double_args' field */
    public java.util.Map<java.lang.CharSequence,java.lang.Double> getEventDoubleArgs() {
      return event_double_args;
    }
    
    /** Sets the value of the 'event_double_args' field */
    public com.demo.hadoop.avro.Event.Builder setEventDoubleArgs(java.util.Map<java.lang.CharSequence,java.lang.Double> value) {
      validate(fields()[13], value);
      this.event_double_args = value;
      fieldSetFlags()[13] = true;
      return this; 
    }
    
    /** Checks whether the 'event_double_args' field has been set */
    public boolean hasEventDoubleArgs() {
      return fieldSetFlags()[13];
    }
    
    /** Clears the value of the 'event_double_args' field */
    public com.demo.hadoop.avro.Event.Builder clearEventDoubleArgs() {
      event_double_args = null;
      fieldSetFlags()[13] = false;
      return this;
    }

    /** Gets the value of the 'attach_fields_1' field */
    public java.lang.Integer getAttachFields1() {
      return attach_fields_1;
    }
    
    /** Sets the value of the 'attach_fields_1' field */
    public com.demo.hadoop.avro.Event.Builder setAttachFields1(int value) {
      validate(fields()[14], value);
      this.attach_fields_1 = value;
      fieldSetFlags()[14] = true;
      return this; 
    }
    
    /** Checks whether the 'attach_fields_1' field has been set */
    public boolean hasAttachFields1() {
      return fieldSetFlags()[14];
    }
    
    /** Clears the value of the 'attach_fields_1' field */
    public com.demo.hadoop.avro.Event.Builder clearAttachFields1() {
      fieldSetFlags()[14] = false;
      return this;
    }

    /** Gets the value of the 'attach_fields_2' field */
    public java.lang.CharSequence getAttachFields2() {
      return attach_fields_2;
    }
    
    /** Sets the value of the 'attach_fields_2' field */
    public com.demo.hadoop.avro.Event.Builder setAttachFields2(java.lang.CharSequence value) {
      validate(fields()[15], value);
      this.attach_fields_2 = value;
      fieldSetFlags()[15] = true;
      return this; 
    }
    
    /** Checks whether the 'attach_fields_2' field has been set */
    public boolean hasAttachFields2() {
      return fieldSetFlags()[15];
    }
    
    /** Clears the value of the 'attach_fields_2' field */
    public com.demo.hadoop.avro.Event.Builder clearAttachFields2() {
      attach_fields_2 = null;
      fieldSetFlags()[15] = false;
      return this;
    }

    /** Gets the value of the 'attach_fields_3' field */
    public java.util.Map<java.lang.CharSequence,java.lang.CharSequence> getAttachFields3() {
      return attach_fields_3;
    }
    
    /** Sets the value of the 'attach_fields_3' field */
    public com.demo.hadoop.avro.Event.Builder setAttachFields3(java.util.Map<java.lang.CharSequence,java.lang.CharSequence> value) {
      validate(fields()[16], value);
      this.attach_fields_3 = value;
      fieldSetFlags()[16] = true;
      return this; 
    }
    
    /** Checks whether the 'attach_fields_3' field has been set */
    public boolean hasAttachFields3() {
      return fieldSetFlags()[16];
    }
    
    /** Clears the value of the 'attach_fields_3' field */
    public com.demo.hadoop.avro.Event.Builder clearAttachFields3() {
      attach_fields_3 = null;
      fieldSetFlags()[16] = false;
      return this;
    }

    /** Gets the value of the 'attach_fields_4' field */
    public java.util.Map<java.lang.CharSequence,java.lang.Integer> getAttachFields4() {
      return attach_fields_4;
    }
    
    /** Sets the value of the 'attach_fields_4' field */
    public com.demo.hadoop.avro.Event.Builder setAttachFields4(java.util.Map<java.lang.CharSequence,java.lang.Integer> value) {
      validate(fields()[17], value);
      this.attach_fields_4 = value;
      fieldSetFlags()[17] = true;
      return this; 
    }
    
    /** Checks whether the 'attach_fields_4' field has been set */
    public boolean hasAttachFields4() {
      return fieldSetFlags()[17];
    }
    
    /** Clears the value of the 'attach_fields_4' field */
    public com.demo.hadoop.avro.Event.Builder clearAttachFields4() {
      attach_fields_4 = null;
      fieldSetFlags()[17] = false;
      return this;
    }

    @Override
    public Event build() {
      try {
        Event record = new Event();
        record.event = fieldSetFlags()[0] ? this.event : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.userid = fieldSetFlags()[1] ? this.userid : (java.lang.Integer) defaultValue(fields()[1]);
        record.uuid = fieldSetFlags()[2] ? this.uuid : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.ip = fieldSetFlags()[3] ? this.ip : (java.lang.CharSequence) defaultValue(fields()[3]);
        record.s_channel = fieldSetFlags()[4] ? this.s_channel : (java.lang.CharSequence) defaultValue(fields()[4]);
        record.self_url = fieldSetFlags()[5] ? this.self_url : (java.lang.CharSequence) defaultValue(fields()[5]);
        record.ref_url = fieldSetFlags()[6] ? this.ref_url : (java.lang.CharSequence) defaultValue(fields()[6]);
        record.app_name = fieldSetFlags()[7] ? this.app_name : (java.lang.CharSequence) defaultValue(fields()[7]);
        record.platform = fieldSetFlags()[8] ? this.platform : (java.lang.CharSequence) defaultValue(fields()[8]);
        record.event_date = fieldSetFlags()[9] ? this.event_date : (java.lang.CharSequence) defaultValue(fields()[9]);
        record.event_time = fieldSetFlags()[10] ? this.event_time : (java.lang.Integer) defaultValue(fields()[10]);
        record.event_attr = fieldSetFlags()[11] ? this.event_attr : (java.util.Map<java.lang.CharSequence,java.lang.CharSequence>) defaultValue(fields()[11]);
        record.event_string_args = fieldSetFlags()[12] ? this.event_string_args : (java.util.Map<java.lang.CharSequence,java.lang.CharSequence>) defaultValue(fields()[12]);
        record.event_double_args = fieldSetFlags()[13] ? this.event_double_args : (java.util.Map<java.lang.CharSequence,java.lang.Double>) defaultValue(fields()[13]);
        record.attach_fields_1 = fieldSetFlags()[14] ? this.attach_fields_1 : (java.lang.Integer) defaultValue(fields()[14]);
        record.attach_fields_2 = fieldSetFlags()[15] ? this.attach_fields_2 : (java.lang.CharSequence) defaultValue(fields()[15]);
        record.attach_fields_3 = fieldSetFlags()[16] ? this.attach_fields_3 : (java.util.Map<java.lang.CharSequence,java.lang.CharSequence>) defaultValue(fields()[16]);
        record.attach_fields_4 = fieldSetFlags()[17] ? this.attach_fields_4 : (java.util.Map<java.lang.CharSequence,java.lang.Integer>) defaultValue(fields()[17]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
